In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
0,Shah Rukh Khan,Chennai Express,2013,Action/Comedy,423,6.1
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama/Action,969,8.0
2,Aamir Khan,Dangal,2016,Sports/Drama,2027,8.4
3,Deepika Padukone,Piku,2015,Comedy/Drama,140,7.6
4,Ranveer Singh,Gully Boy,2019,Musical/Drama,238,8.0
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377,8.1
6,Hrithik Roshan,War,2019,Action/Thriller,475,6.5
7,Alia Bhatt,Raazi,2018,Thriller/Drama,220,7.8
8,Ranbir Kapoor,Sanju,2018,Biography/Drama,586,7.7
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137,8.2

In [8]:
df = df[df['IMDB']>8.0]
df

,ACTOR,FILM,YEAR,GENRE,BOXOFFICE,IMDB
2,Aamir Khan,Dangal,2016,Sports/Drama,2027,8.4
5,Katrina Kaif,Zindagi Na Milegi Dobara,2011,Adventure/Drama,377,8.1
9,Kangana Ranaut,Queen,2014,Comedy/Drama,137,8.2

In [11]:
df.to_csv("data_updated.csv")   ##if you dont want indexing do --> index= False

we can DO with json data as well for thatif json is nested then we jave to normalise that fist... -->>see notes for that